# Generated by Django 5.2.17 on 2026-09-30 11:25

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Classe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="رمز القسم"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="الترتيب"),
                ),
            ],
            options={
                "verbose_name": "قسم",
                "verbose_name_plural": "الأقسام",
                "ordering": ["order", "code"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "مشرف"),
                            ("teacher", "أستاذ"),
                            ("student", "تلميذ"),
                        ],
                        default="student",
                        max_length=10,
                        verbose_name="الدور",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="الاسم الكامل"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "classe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="students",
                        to="quiz.classe",
                        verbose_name="القسم (للتلميذ)",
                    ),
                ),
                (
                    "teaching_classes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="teachers",
                        to="quiz.classe",
                        verbose_name="الأقسام التي يدرسها",
                    ),
                ),
            ],
            options={
                "verbose_name": "مستخدم",
                "verbose_name_plural": "المستخدمون",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="عنوان الامتحان"),
                ),
                ("instructions", models.TextField(blank=True, verbose_name="تعليمات")),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=30, verbose_name="المدة (بالدقائق)"
                    ),
                ),
                (
                    "available_from",
                    models.DateTimeField(blank=True, null=True, verbose_name="متاح من"),
                ),
                (
                    "available_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="متاح حتى"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="منشور للتلاميذ"),
                ),
                (
                    "show_result",
                    models.BooleanField(
                        default=True, verbose_name="إظهار النتيجة للتلميذ بعد التسليم"
                    ),
                ),
                (
                    "shuffle_questions",
                    models.BooleanField(
                        default=False, verbose_name="خلط ترتيب الأسئلة"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "classe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="quiz.classe",
                        verbose_name="القسم",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="الأستاذ",
                    ),
                ),
            ],
            options={
                "verbose_name": "امتحان",
                "verbose_name_plural": "الامتحانات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Attempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("in_progress", "جارٍ"), ("submitted", "مُسلَّم")],
                        default="in_progress",
                        max_length=15,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="بداية"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="التسليم"),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=7, verbose_name="النقطة"
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=7,
                        verbose_name="المجموع",
                    ),
                ),
                (
                    "violations",
                    models.PositiveIntegerField(
                        default=0, verbose_name="محاولات الخروج"
                    ),
                ),
                (
                    "auto_submitted",
                    models.BooleanField(default=False, verbose_name="سُلّم تلقائياً"),
                ),
                ("question_order", models.JSONField(blank=True, default=list)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="التلميذ",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="quiz.exam",
                        verbose_name="الامتحان",
                    ),
                ),
            ],
            options={
                "verbose_name": "محاولة",
                "verbose_name_plural": "المحاولات",
                "unique_together": {("exam", "student")},
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="نص السؤال")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="questions/",
                        verbose_name="صورة توضيحية",
                    ),
                ),
                (
                    "points",
                    models.DecimalField(
                        decimal_places=2, default=1, max_digits=6, verbose_name="النقاط"
                    ),
                ),
                (
                    "correct_answer",
                    models.CharField(
                        help_text="حرف الخيار الصحيح: A أو B أو C أو D ...",
                        max_length=1,
                        verbose_name="رمز الإجابة الصحيحة",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="quiz.exam",
                        verbose_name="الامتحان",
                    ),
                ),
            ],
            options={
                "verbose_name": "سؤال",
                "verbose_name_plural": "الأسئلة",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="المادة"
                    ),
                ),
                (
                    "classes",
                    models.ManyToManyField(
                        related_name="subjects",
                        to="quiz.classe",
                        verbose_name="الأقسام",
                    ),
                ),
            ],
            options={
                "verbose_name": "مادة",
                "verbose_name_plural": "المواد",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="exam",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exams",
                to="quiz.subject",
                verbose_name="المادة",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="teaching_subjects",
            field=models.ManyToManyField(
                blank=True,
                related_name="teachers",
                to="quiz.subject",
                verbose_name="المواد التي يدرسها",
            ),
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("letter", models.CharField(max_length=1, verbose_name="الرمز")),
                ("text", models.CharField(max_length=500, verbose_name="نص الخيار")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="quiz.question",
                    ),
                ),
            ],
            options={
                "ordering": ["letter"],
                "unique_together": {("question", "letter")},
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("selected", models.CharField(blank=True, max_length=1)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="quiz.attempt",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quiz.question"
                    ),
                ),
            ],
            options={
                "unique_together": {("attempt", "question")},
            },
        ),
    ]
