# Generated by Django 5.2.17 on 2026-09-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_seed_classes_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='changes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='level',
            field=models.CharField(blank=True, choices=[('E', 'بسيط'), ('M', 'متوسط'), ('H', 'صعب')], max_length=1, verbose_name='المستوى'),
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.CharField(blank=True, help_text='الدرس أو المحور الذي يقيسه السؤال (يُستعمل في تقرير التلميذ).', max_length=100, verbose_name='المحور'),
        ),
    ]
