# Generated by Django 5.2.17 on 2026-10-03 09:48

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0003_question_level_topic_answer_time"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={
                "base_manager_name": "all_objects",
                "ordering": ["order", "id"],
                "verbose_name": "سؤال",
                "verbose_name_plural": "الأسئلة",
            },
        ),
        migrations.AlterModelManagers(
            name="question",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="question",
            name="archived",
            field=models.BooleanField(default=False, verbose_name="مؤرشف"),
        ),
    ]
