# Generated by Django 5.2.18 on 2026-10-08 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0004_question_archived"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="اسم الأستاذ"
                    ),
                ),
                (
                    "subject",
                    models.CharField(blank=True, max_length=100, verbose_name="المادة"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="في اللائحة"),
                ),
            ],
            options={
                "verbose_name": "أستاذ (الحضور)",
                "verbose_name_plural": "الأساتذة (الحضور)",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="guardian_phone",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="هاتف الوكيل"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="guardian_phone2",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="هاتف الوكيل 2"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="matricule",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                unique=True,
                verbose_name="رقم القيد",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="whatsapp",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="رقم الواتساب"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "مشرف"),
                    ("teacher", "أستاذ"),
                    ("student", "تلميذ"),
                    ("supervisor", "مراقب"),
                ],
                default="student",
                max_length=10,
                verbose_name="الدور",
            ),
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="رمز القسم"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="الترتيب"),
                ),
                (
                    "classe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="quiz.classe",
                        verbose_name="المستوى",
                    ),
                ),
            ],
            options={
                "verbose_name": "قسم (فصل)",
                "verbose_name_plural": "الأقسام (الفصول)",
                "ordering": ["order", "code"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="quiz.section",
                verbose_name="الفصل (للتلميذ)",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="supervised_sections",
            field=models.ManyToManyField(
                blank=True,
                related_name="supervisors",
                to="quiz.section",
                verbose_name="الأقسام التي يراقبها",
            ),
        ),
        migrations.CreateModel(
            name="StudentNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="التاريخ")),
                ("text", models.TextField(verbose_name="الملاحظة")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="التلميذ",
                    ),
                ),
            ],
            options={
                "verbose_name": "ملاحظة",
                "verbose_name_plural": "الملاحظات اليومية",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="التاريخ")),
                (
                    "status",
                    models.CharField(
                        choices=[("P", "حاضر"), ("A", "غائب"), ("L", "متأخر")],
                        default="P",
                        max_length=1,
                        verbose_name="الحالة",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="quiz.section",
                        verbose_name="الفصل",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="التلميذ",
                    ),
                ),
            ],
            options={
                "verbose_name": "حضور تلميذ",
                "verbose_name_plural": "حضور التلاميذ",
                "ordering": ["-date"],
                "unique_together": {("student", "date")},
            },
        ),
        migrations.CreateModel(
            name="TeacherAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="التاريخ")),
                (
                    "status",
                    models.CharField(
                        choices=[("P", "حاضر"), ("A", "غائب"), ("L", "متأخر")],
                        default="P",
                        max_length=1,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=255, verbose_name="ملاحظة"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance",
                        to="quiz.teacher",
                        verbose_name="الأستاذ",
                    ),
                ),
            ],
            options={
                "verbose_name": "حضور أستاذ",
                "verbose_name_plural": "حضور الأساتذة",
                "ordering": ["-date"],
                "unique_together": {("teacher", "date")},
            },
        ),
    ]
