# Generated by Django 5.2.18 on 2026-10-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0006_seed_sections"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherattendance",
            name="sections",
            field=models.ManyToManyField(
                blank=True,
                related_name="teacher_attendance",
                to="quiz.section",
                verbose_name="الأقسام",
            ),
        ),
    ]
